---
abstract: Prebuilt
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Aspect::Library::Timer
name: Aspect-Library-Timer
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Aspect::Modular: 1.00
  Params::Util: 1.00
  Time::HiRes: 1.9718
  perl: 5.8.2
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Aspect-Library-Timer
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Aspect-Library-Timer
version: 1.10
